# Generated by Django 5.2.8 on 2025-11-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
